[package]
name    = "rem-transient"
version.workspace = true
edition = "2021"

[dependencies]
rem-core      = { workspace = true }
rem-config    = { workspace = true }
rem-mesh      = { workspace = true }
rem-materials = { workspace = true }
rem-parallel  = { workspace = true }
rem-electrostatic = { workspace = true }
rem-eigenmode     = { workspace = true }
log           = { workspace = true }
