[package]
name    = "rem-electrostatic"
version = "0.1.0"
edition = "2021"

[dependencies]
rem-core      = { workspace = true }
rem-config    = { workspace = true }
rem-mesh      = { workspace = true }
rem-materials = { workspace = true }
rem-parallel  = { workspace = true }
rem-bc        = { workspace = true }
rem-result    = { workspace = true }
fem-assembly  = { workspace = true }
fem-space     = { workspace = true }
fem-linalg    = { workspace = true }
log           = { workspace = true }
