[package]
name    = "rem-cli"
version.workspace = true
edition = "2021"

[[bin]]
name = "rem"
path = "src/main.rs"

[dependencies]
rem-core          = { workspace = true }
rem-config        = { workspace = true }
rem-mesh          = { workspace = true, features = ["metis"] }
rem-materials     = { workspace = true }
rem-parallel      = { workspace = true }
rem-electrostatic = { workspace = true }
rem-magnetostatic = { workspace = true }
rem-eigenmode     = { workspace = true }
rem-driven        = { workspace = true }
rem-transient     = { workspace = true }
rem-mom           = { workspace = true }
rem-optim         = { workspace = true }
rem-sbr           = { workspace = true }
rem-febi          = { workspace = true }
rem-ddm           = { workspace = true }
rem-bem           = { workspace = true }
rem-planar        = { workspace = true }
rem-convert       = { workspace = true }
clap              = { workspace = true }
anyhow            = { workspace = true }
env_logger        = { workspace = true }
log               = { workspace = true }
serde_json        = { workspace = true }
