// crates/touchstone/src/write.rs
use num_complex::Complex64;

/// Touchstone data format for the option line.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum TsFormat { Ri, Ma, Db }

/// Frequency unit for the option line.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum TsFreqUnit { Hz, Khz, Mhz, Ghz }

impl TsFreqUnit {
    pub fn scale(&self) -> f64 {
        match self {
            TsFreqUnit::Hz  => 1.0,
            TsFreqUnit::Khz => 1e3,
            TsFreqUnit::Mhz => 1e6,
            TsFreqUnit::Ghz => 1e9,
        }
    }
    pub fn label(&self) -> &'static str {
        match self {
            TsFreqUnit::Hz  => "Hz",
            TsFreqUnit::Khz => "KHz",
            TsFreqUnit::Mhz => "MHz",
            TsFreqUnit::Ghz => "GHz",
        }
    }
}

/// Write an N-port Touchstone file as a String.
pub fn write_snp(
    freqs_hz: &[f64],
    s_data: &[Vec<Complex64>],
    n_ports: usize,
    z0: f64,
    fmt: TsFormat,
    unit: TsFreqUnit,
) -> String {
    assert_eq!(freqs_hz.len(), s_data.len(), "freq/s_data length mismatch");
    let fmt_str = match fmt {
        TsFormat::Ri => "RI",
        TsFormat::Ma => "MA",
        TsFormat::Db => "DB",
    };
    let mut out = String::new();
    out.push_str(&format!("! Touchstone S{}P generated by rem2 EM solver\n", n_ports));
    out.push_str(&format!("# {} S {} R {}\n", unit.label(), fmt_str, z0));
    let freq_scale = unit.scale();
    for (fi, &fhz) in freqs_hz.iter().enumerate() {
        let row = &s_data[fi];
        let freq_scaled = fhz / freq_scale;
        let mut pairs: Vec<String> = row.iter().map(|&s| match fmt {
            TsFormat::Ri => format!("  {:.8e}  {:.8e}", s.re, s.im),
            TsFormat::Ma => {
                let mag = s.norm();
                let ang = s.im.atan2(s.re).to_degrees();
                format!("  {:.8e}  {:.6}", mag, ang)
            }
            TsFormat::Db => {
                let db = if s.norm() > 1e-300 { 20.0 * s.norm().log10() } else { -999.0 };
                let ang = s.im.atan2(s.re).to_degrees();
                format!("  {:.6}  {:.6}", db, ang)
            }
        }).collect();
        if n_ports <= 2 {
            let line: String = std::iter::once(format!("{:.9e}", freq_scaled))
                .chain(pairs.drain(..))
                .collect::<Vec<_>>()
                .join("");
            out.push_str(&line);
            out.push('\n');
        } else {
            let mut chunks = pairs.chunks(4);
            if let Some(first) = chunks.next() {
                let line = format!("{:.9e}", freq_scaled) + &first.join("");
                out.push_str(&line);
                out.push('\n');
            }
            for chunk in chunks {
                let line = "          ".to_string() + &chunk.join("");
                out.push_str(&line);
                out.push('\n');
            }
        }
    }
    out
}

/// Write an N-port Touchstone v2 file as a String (IEEE 370-2016).
///
/// Generates `[Version]`, `[Number of Ports]`, `[Number of Frequencies]`,
/// `[Reference]`, `[Network Data]`, and `[End]` keywords.
///
/// `comments` — optional header comment strings (written as `! ...` lines).
pub fn write_snp_v2(
    freqs_hz: &[f64],
    s_data: &[Vec<Complex64>],
    n_ports: usize,
    z0: f64,
    fmt: TsFormat,
    unit: TsFreqUnit,
    comments: &[&str],
) -> String {
    assert_eq!(freqs_hz.len(), s_data.len(), "freq/s_data length mismatch");
    let fmt_str = match fmt {
        TsFormat::Ri => "RI",
        TsFormat::Ma => "MA",
        TsFormat::Db => "DB",
    };
    let mut out = String::new();
    out.push_str("! Touchstone v2 S-parameter file generated by rem2 EM solver\n");
    for c in comments {
        out.push_str(&format!("! {c}\n"));
    }
    out.push_str("[Version] 2.0\n");
    out.push_str(&format!("# {} S {} R {}\n", unit.label(), fmt_str, z0));
    out.push_str(&format!("[Number of Ports] {n_ports}\n"));
    out.push_str(&format!("[Number of Frequencies] {}\n", freqs_hz.len()));
    let refs: Vec<String> = (0..n_ports).map(|_| format!("{z0}")).collect();
    out.push_str(&format!("[Reference] {}\n", refs.join(" ")));
    out.push_str("[Network Data]\n");
    let freq_scale = unit.scale();
    for (fi, &fhz) in freqs_hz.iter().enumerate() {
        let row = &s_data[fi];
        let freq_scaled = fhz / freq_scale;
        let mut pairs: Vec<String> = row.iter().map(|&s| match fmt {
            TsFormat::Ri => format!("  {:.8e}  {:.8e}", s.re, s.im),
            TsFormat::Ma => {
                let mag = s.norm();
                let ang = s.im.atan2(s.re).to_degrees();
                format!("  {:.8e}  {:.6}", mag, ang)
            }
            TsFormat::Db => {
                let db = if s.norm() > 1e-300 { 20.0 * s.norm().log10() } else { -999.0 };
                let ang = s.im.atan2(s.re).to_degrees();
                format!("  {:.6}  {:.6}", db, ang)
            }
        }).collect();
        if n_ports <= 2 {
            let line: String = std::iter::once(format!("{:.9e}", freq_scaled))
                .chain(pairs.drain(..))
                .collect::<Vec<_>>()
                .join("");
            out.push_str(&line);
            out.push('\n');
        } else {
            let mut chunks = pairs.chunks(4);
            if let Some(first) = chunks.next() {
                let line = format!("{:.9e}", freq_scaled) + &first.join("");
                out.push_str(&line);
                out.push('\n');
            }
            for chunk in chunks {
                let line = "          ".to_string() + &chunk.join("");
                out.push_str(&line);
                out.push('\n');
            }
        }
    }
    out.push_str("[End]\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use num_complex::Complex64;

    fn s1p_sample() -> (Vec<f64>, Vec<Vec<Complex64>>) {
        let freqs = vec![1e9, 2e9, 3e9];
        let s_data = vec![
            vec![Complex64::new(0.5, -0.3)],
            vec![Complex64::new(0.4, -0.2)],
            vec![Complex64::new(0.3, -0.1)],
        ];
        (freqs, s_data)
    }

    #[test]
    fn option_line_s1p() {
        let (f, s) = s1p_sample();
        let out = write_snp(&f, &s, 1, 50.0, TsFormat::Ri, TsFreqUnit::Ghz);
        assert!(out.contains("# GHz S RI R 50"), "option line missing: {out}");
    }

    #[test]
    fn correct_number_of_data_lines_s1p() {
        let (f, s) = s1p_sample();
        let out = write_snp(&f, &s, 1, 50.0, TsFormat::Ri, TsFreqUnit::Ghz);
        let data_lines: Vec<&str> = out.lines()
            .filter(|l| !l.starts_with('!') && !l.starts_with('#') && !l.trim().is_empty())
            .collect();
        assert_eq!(data_lines.len(), 3, "expected 3 data lines, got {data_lines:?}");
    }

    #[test]
    fn ri_values_present_s1p() {
        let (f, s) = s1p_sample();
        let out = write_snp(&f, &s, 1, 50.0, TsFormat::Ri, TsFreqUnit::Ghz);
        let first_data = out.lines()
            .find(|l| !l.starts_with('!') && !l.starts_with('#') && !l.trim().is_empty())
            .unwrap();
        let parts: Vec<f64> = first_data.split_whitespace()
            .map(|p| p.parse::<f64>().unwrap())
            .collect();
        assert_eq!(parts.len(), 3, "S1P data line needs 3 fields: {first_data}");
        assert!((parts[0] - 1.0).abs() < 1e-6, "freq should be 1.0 GHz: {}", parts[0]);
        assert!((parts[1] - 0.5).abs() < 1e-6, "Re(S11) wrong: {}", parts[1]);
        assert!((parts[2] - (-0.3)).abs() < 1e-6, "Im(S11) wrong: {}", parts[2]);
    }

    #[test]
    fn s2p_has_four_s_values_per_freq() {
        let freqs = vec![1e9];
        let s_data = vec![vec![
            Complex64::new(0.1, 0.0),
            Complex64::new(0.9, 0.0),
            Complex64::new(0.9, 0.0),
            Complex64::new(0.1, 0.0),
        ]];
        let out = write_snp(&freqs, &s_data, 2, 50.0, TsFormat::Ri, TsFreqUnit::Ghz);
        let data_lines: Vec<&str> = out.lines()
            .filter(|l| !l.starts_with('!') && !l.starts_with('#') && !l.trim().is_empty())
            .collect();
        assert!(!data_lines.is_empty());
        let fields: Vec<&str> = data_lines[0].split_whitespace().collect();
        assert_eq!(fields.len(), 9, "S2P line should have 9 fields: {data_lines:?}");
    }

    #[test]
    fn s3p_uses_multiline_layout() {
        let freqs = vec![1e9, 2e9];
        let row: Vec<Complex64> = (0..9).map(|i| Complex64::new(i as f64 * 0.1, 0.0)).collect();
        let s_data = vec![row.clone(), row];
        let out = write_snp(&freqs, &s_data, 3, 50.0, TsFormat::Ri, TsFreqUnit::Ghz);
        let all_lines: Vec<&str> = out.lines()
            .filter(|l| !l.starts_with('!') && !l.starts_with('#') && !l.trim().is_empty())
            .collect();
        assert_eq!(all_lines.len(), 6, "expected 6 data/continuation lines: {all_lines:?}");
        let fields0: Vec<&str> = all_lines[0].split_whitespace().collect();
        assert_eq!(fields0.len(), 9, "first line wrong: {:?}", all_lines[0]);
        let fields1: Vec<&str> = all_lines[1].split_whitespace().collect();
        assert_eq!(fields1.len(), 8, "continuation line wrong: {:?}", all_lines[1]);
        let fields2: Vec<&str> = all_lines[2].split_whitespace().collect();
        assert_eq!(fields2.len(), 2, "last continuation wrong: {:?}", all_lines[2]);
    }

    #[test]
    fn write_snp_v2_keywords() {
        let freqs = vec![1e9, 2e9];
        let s_data = vec![
            vec![Complex64::new(0.1, -0.2)],
            vec![Complex64::new(0.3, -0.4)],
        ];
        let out = write_snp_v2(&freqs, &s_data, 1, 50.0, TsFormat::Ri, TsFreqUnit::Ghz, &[]);
        assert!(out.contains("[Version] 2.0"), "missing [Version]: {out}");
        assert!(out.contains("[Number of Ports] 1"), "missing [Number of Ports]: {out}");
        assert!(out.contains("[Number of Frequencies] 2"), "missing [Number of Frequencies]: {out}");
        assert!(out.contains("[Network Data]"), "missing [Network Data]: {out}");
        assert!(out.contains("[End]"), "missing [End]: {out}");
        assert!(out.contains("[Reference]"), "missing [Reference]: {out}");
    }
}