[package]
name    = "rem-yew"
version = "0.1.0"
edition = "2021"

[dependencies]
yew          = { version = "0.21", features = ["csr"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = "0.4"
web-sys      = { version = "0.3", features = ["HtmlSelectElement", "HtmlInputElement"] }
gloo         = { version = "0.11", features = ["futures"] }
serde        = { workspace = true }
serde_json   = { workspace = true }
log          = { workspace = true }
console_log  = "1.0"
console_error_panic_hook = { workspace = true }

rem-core          = { workspace = true }
rem-config        = { workspace = true }
rem-mesh          = { workspace = true, features = ["metis-wasm"] }
rem-materials     = { workspace = true }
rem-parallel      = { workspace = true }
rem-electrostatic = { workspace = true }
rem-magnetostatic = { workspace = true }
