[package]
name    = "rem-optim"
version = "0.1.0"
edition = "2021"

[dependencies]
rem-config = { workspace = true }
rem-core   = { workspace = true }
rem-mom    = { workspace = true }
rem-mesh   = { workspace = true }
rem-parallel = { workspace = true }
num-complex = { workspace = true }
log = "0.4"
serde_json = { workspace = true }
