[package]
name    = "rem-ddm"
version.workspace = true
edition = "2021"

[dependencies]
rem-core      = { workspace = true }
rem-config    = { workspace = true }
rem-mesh      = { workspace = true }
rem-parallel  = { workspace = true }
nalgebra      = { workspace = true }
num-complex   = { workspace = true }
thiserror     = { workspace = true }
log           = { workspace = true }
rmetis        = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rayon = "1"

[dev-dependencies]
approx = "0.5"
