[package]
name    = "rem-driven"
version.workspace = true
edition = "2021"

[dependencies]
rem-core      = { workspace = true }
rem-config    = { workspace = true }
rem-mesh      = { workspace = true }
rem-materials = { workspace = true }
rem-parallel  = { workspace = true }
rem-electrostatic = { workspace = true }
rem-eigenmode     = { workspace = true }
num-complex = { workspace = true }
nalgebra    = { workspace = true }
log         = { workspace = true }
rem-touchstone = { workspace = true }
fem-assembly = { workspace = true }
fem-space    = { workspace = true }
fem-element  = { workspace = true }
fem-mesh     = { workspace = true }
